### ISSUE TITLE
👀 Mr. Grammar here, just making sure you're doing it right

### ISSUE THREAD

**Issue by YhvrWasTaken** [TheTastyPi/Timewalls-The-Game#4]
**README.md** _(but, like, the grammar is gooder)_
Timewalls: The Game

"Timewall": When you have to wait a certain amount of time ~~in order~~ to progress, especially with minimal interaction and when the duration is absurdly long and unnecessary.

So technically all game(+s) are filled with timewalls.

**Comment by TheTastyPi** [comment]
~~Gooder is not a word you idiot.~~ The readme is gonna be changed next update, but thanks anyway.
